### ISSUE TITLE
Sending Request

### ISSUE THREAD

**Issue by LuHe78** [Adomix/PushBulletNet#8]
Thanks for your great work. 

Sending Notfications to devices works great. But is there also a possibility to send a request to a friend in a chat or only on my own devices?

Regards

**Comment by ghost** [comment]
@LuHe78 I can check that for you. Please allow me a few hours. I am currently in college. :ok_hand:

**Comment by ghost** [comment]
Great question, thank you. However, with the API plug and go is not possible in this scenario. Your friend will need to add the source device that the notification is coming from as a device. On the flip side, you can also add their device on your devices through pushbullet.
This is because PushBullet registers user devices through an oauth2 style process, without clicking the prompt to accept their data, you may not communicate with that device. 
[New device](https://www.pushbullet.com/#devices/new)

**Comment by ghost** [comment]
I will leave this open for a bit incase you have further questions.
